function [fitresult, gof] = createFit02(xx, yyc)
%CREATEFIT(XX,YYC)
%  Create a fit.
%  
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: yyc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 17-Dec-2013 19:46:59
 

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, yyc );

% Set up fittype and options.
ft = fittype( 'rat02' );
opts = fitoptions( ft );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.855363532293014 0.148527442296314 0.601439381121039];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'yyc vs. xx', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'xx' );
% ylabel( 'yyc' );
% grid on


