function [fitresult, gof] = createFit03(xx, yyr)
%CREATEFIT(XX,YYR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: yyr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Dec-2013 22:54:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, yyr );

% Set up fittype and options.
ft = fittype( 'rat03' );
opts = fitoptions( ft );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.StartPoint = [0.550710117668191 0.646487511813822 0.545148281028438 0.345579734056491];
opts.Upper = [Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'yyr vs. xx', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'xx' );
% ylabel( 'yyr' );
% grid on


