function [fitresult, gof] = createFit3s(xx, yyi)
%CREATEFIT(XX,YYI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: yyi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Dec-2013 18:56:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, yyi );

% Set up fittype and options.
ft = fittype( 'a/((x-b)^3)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Algorithm = 'Trust-Region';
opts.Display = 'Off';
opts.Lower = [-Inf 0];
opts.StartPoint = [0 0];
opts.Upper = [Inf min(xx)];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'yyi vs. xx', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'xx' );
% ylabel( 'yyi' );
% grid on


